apiVersion: apps/v1
kind: Deployment
metadata:
  name: isee
spec:
  selector:
    matchLabels:
      app: isee
  replicas: 3
  template:
    metadata:
      name: isee
      labels:
        app: isee
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: isee-pvc
      containers:
      - image: quay.io/cellgeni/isee:v0.1.2
        imagePullPolicy: IfNotPresent
        name: isee
        volumeMounts:
        - name: data
          mountPath: /data/
        ports:
        - containerPort: 3838
          name: isee
        environ:
          R_ENVIRON: /data/Renviron.site
        resources:
          requests:
            memory: "8Gi"
            cpu: 1
          limits:
            memory: "16Gi"
            cpu: 4
      initContainers:
      - name: pull-data
        image: quay.io/cellgeni/isee:fetch-data-v0.3.3
        command: ['bash', 'get-data.sh']
        volumeMounts:
          - name: data
            mountPath: /data
