apiVersion: apps/v1
kind: Deployment
metadata:
  name: isee
spec:
  selector:
    matchLabels:
      app: isee
  replicas: 1
  template:
    metadata:
      name: isee
      labels:
        app: isee
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: isee-pvc
      containers:
      - image: quay.io/cellgeni/isee:v0.1.3
        imagePullPolicy: IfNotPresent
        name: isee
        volumeMounts:
        - name: data
          mountPath: /data/
        ports:
        - containerPort: 3838
          hostPort: 13838
          name: isee
        resources:
          requests:
            memory: "8Gi"
            cpu: 1
          limits:
            memory: "16Gi"
            cpu: 4
        livenessProbe:
          httpGet:
            path: /treg-tomas/ss2_human
            port: isee
          initialDelaySeconds: 10
          timeoutSeconds: 10
          periodSeconds: 240
      initContainers:
      - name: pull-data
        image: quay.io/cellgeni/isee:fetch-data-v0.3.6
        command: ['bash', 'get-data.sh']
        volumeMounts:
          - name: data
            mountPath: /data
