apiVersion: apps/v1
kind: Deployment
metadata:
  name: ss2-human
spec:
  selector:
    matchLabels:
      app: ss2-human
  replicas: 1
  template:
    metadata:
      name: ss2-human
      labels:
        app: ss2-human
    spec:
      containers:
      - image: quay.io/cellgeni/isee:treg-tomas-ss2_human-0.0.9
        imagePullPolicy: IfNotPresent
        name: ss2-human
        ports:
        - containerPort: 1234
          name: isee
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tenx-skin
spec:
  selector:
    matchLabels:
      app: tenx-skin
  replicas: 1
  template:
    metadata:
      name: tenx-skin
      labels:
        app: tenx-skin
    spec:
      containers:
      - image: quay.io/cellgeni/isee:treg-tomas-tenx_Skin-0.0.1
        imagePullPolicy: IfNotPresent
        name: tenx-skin
        ports:
        - containerPort: 1234
          name: isee
        resources:
          requests:
            memory: "3Gi"
            cpu: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tenx-tmembln
spec:
  selector:
    matchLabels:
      app: tenx-tmembln
  replicas: 1
  template:
    metadata:
      name: tenx-tmembln
      labels:
        app: tenx-tmembln
    spec:
      containers:
      - image: quay.io/cellgeni/isee:treg-tomas-tenx_TmembLN-0.0.1
        imagePullPolicy: IfNotPresent
        name: tenx-tmembln
        ports:
        - containerPort: 1234
          name: isee
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tenx-tmemcolon
spec:
  selector:
    matchLabels:
      app: tenx-tmemcolon
  replicas: 1
  template:
    metadata:
      name: tenx-tmemcolon
      labels:
        app: tenx-tmemcolon
    spec:
      containers:
      - image: quay.io/cellgeni/isee:treg-tomas-tenx_TmemColon-0.0.1
        imagePullPolicy: IfNotPresent
        name: tenx-tmemcolon
        ports:
        - containerPort: 1234
          name: isee
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tenx-tmemmln
spec:
  selector:
    matchLabels:
      app: tenx-tmemmln
  replicas: 1
  template:
    metadata:
      name: tenx-tmemmln
      labels:
        app: tenx-tmemmln
    spec:
      containers:
      - image: quay.io/cellgeni/isee:treg-tomas-tenx_TmemmLN-0.0.1
        imagePullPolicy: IfNotPresent
        name: tenx-tmemmln
        ports:
        - containerPort: 1234
          name: isee
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tenx-tmemspleen
spec:
  selector:
    matchLabels:
      app: tenx-tmemspleen
  replicas: 1
  template:
    metadata:
      name: tenx-tmemspleen
      labels:
        app: tenx-tmemspleen
    spec:
      containers:
      - image: quay.io/cellgeni/isee:treg-tomas-tenx_TmemSpleen-0.0.1
        imagePullPolicy: IfNotPresent
        name: tenx-tmemspleen
        ports:
        - containerPort: 1234
          name: isee
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tenx-tregbln
spec:
  selector:
    matchLabels:
      app: tenx-tregbln
  replicas: 1
  template:
    metadata:
      name: tenx-tregbln
      labels:
        app: tenx-tregbln
    spec:
      containers:
      - image: quay.io/cellgeni/isee:treg-tomas-tenx_TregbLN-0.0.1
        imagePullPolicy: IfNotPresent
        name: tenx-tregbln
        ports:
        - containerPort: 1234
          name: isee
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tenx-tregcolon
spec:
  selector:
    matchLabels:
      app: tenx-tregcolon
  replicas: 1
  template:
    metadata:
      name: tenx-tregcolon
      labels:
        app: tenx-tregcolon
    spec:
      containers:
      - image: quay.io/cellgeni/isee:treg-tomas-tenx_TregColon-0.0.1
        imagePullPolicy: IfNotPresent
        name: tenx-tregcolon
        ports:
        - containerPort: 1234
          name: isee
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tenx-tregmln
spec:
  selector:
    matchLabels:
      app: tenx-tregmln
  replicas: 1
  template:
    metadata:
      name: tenx-tregmln
      labels:
        app: tenx-tregmln
    spec:
      containers:
      - image: quay.io/cellgeni/isee:treg-tomas-tenx_TregmLN-0.0.1
        imagePullPolicy: IfNotPresent
        name: tenx-tregmln
        ports:
        - containerPort: 1234
          name: isee
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tenx-tregspleen
spec:
  selector:
    matchLabels:
      app: tenx-tregspleen
  replicas: 1
  template:
    metadata:
      name: tenx-tregspleen
      labels:
        app: tenx-tregspleen
    spec:
      containers:
      - image: quay.io/cellgeni/isee:treg-tomas-tenx_TregSpleen-0.0.1
        imagePullPolicy: IfNotPresent
        name: tenx-tregspleen
        ports:
        - containerPort: 1234
          name: isee
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ss2-mousemelanoma
spec:
  selector:
    matchLabels:
      app: ss2-mousemelanoma
  replicas: 1
  template:
    metadata:
      name: ss2-mousemelanoma
      labels:
        app: ss2-mousemelanoma
    spec:
      containers:
      - image: quay.io/cellgeni/isee:treg-tomas-ss2_mouseMelanoma-0.0.1
        imagePullPolicy: IfNotPresent
        name: ss2-mousemelanoma
        ports:
        - containerPort: 1234
          name: isee
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ss2-mouseskin
spec:
  selector:
    matchLabels:
      app: ss2-mouseskin
  replicas: 1
  template:
    metadata:
      name: ss2-mouseskin
      labels:
        app: ss2-mouseskin
    spec:
      containers:
      - image: quay.io/cellgeni/isee:treg-tomas-ss2_mouseSkin-0.0.1
        imagePullPolicy: IfNotPresent
        name: ss2-mouseskin
        ports:
        - containerPort: 1234
          name: isee
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ss2-mousecolon
spec:
  selector:
    matchLabels:
      app: ss2-mousecolon
  replicas: 1
  template:
    metadata:
      name: ss2-mousecolon
      labels:
        app: ss2-mousecolon
    spec:
      containers:
      - image: quay.io/cellgeni/isee:treg-tomas-ss2_mouseColon-0.0.2
        imagePullPolicy: IfNotPresent
        name: ss2-mousecolon
        ports:
        - containerPort: 1234
          name: isee