apiVersion: v1
kind: PersistentVolume
metadata:
  name: isee
spec:
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  glusterfs:
    endpoints: glusterfs
    path: gluster
    readOnly: false
